id: I4B7AC29E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T08:41:49+00:00'
last_modified: '2022-06-08T17:15:28.082688+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC41
  title: དབུ་མའི་སྤྱི་དོན་བློ་གསལ་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B474:
      image_group_id: I2PD17598
      title: ''
      total_pages: 508
      order: 1
      base_file: B474.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
