id: I4B7AC29E
legacy_id: P010750
ocr_import_info:
  bdrc_scan_id: W1AC41
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T08:38:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:19:54.351462+00:00'
last_modified: 2022-08-31 02:20:37.846446
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC41
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC41
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མའི་སྤྱི་དོན་བློ་གསལ་སྒྲོན་མེ།
  author: ཁྲི ༢༢་དགེ་འདུན་བསྟན་པ་དར་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.6809684008602894
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I2PD17598:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD17598
      total_pages: 508
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD17598.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.6809684008602894
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
